version: '3'
services:
  wanredis:
    container_name: redis0
    image: redis
    restart: always
    ports:
      - 6789:6789
    privileged: true
#    fixme 文件目录不存在时会将文件映射成目录 所以这里配置了command会启动失败
    command: redis-server /etc/redis/redis.conf --appendonly yes
    volumes:
#      - 需要自己配置映射关系
      - /Users/wan/workspace/wan/wan_go/volumes/redis/data:/data
      - /Users/wan/workspace/wan/wan_go/volumes/redis/conf/redis.conf:/etc/redis/redis.conf
    networks:
      - wannet

networks:

  wannet:
    driver: bridge
